export const storageKeys = {
  theme: 'theme',
  auth: 'auth:user',
  users: 'auth:users',
  vendors: 'vendors',
  products: 'catalog:products',
  categories: 'catalog:categories',
  reviews: 'catalog:reviews',
  cart: 'cart',
  orders: 'orders',
  movements: 'inventory:movements',
  wishlist: 'wishlist',
  settings: 'settings',
  discounts: 'discounts',
  authToken: 'auth:token',
} as const
